version: '3.8'

services:
  sities_scraper:
    image: luisarias/foursquare_sities_scraper:latest
    container_name: foursquare_sities_prod
    restart: always
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_POOL_SIZE: ${MONGODB_POOL_SIZE}
      MONGODB_TIMEOUT_MS: ${MONGODB_TIMEOUT_MS}
      PARALLEL_PROCESSES: ${PARALLEL_PROCESSES}
      RATE_LIMIT_PER_HOUR: ${RATE_LIMIT_PER_HOUR}
    volumes:
      - ./logs:/app/logs
      - ./caribbean_grid/data/zonas_departamentos:/app/caribbean_grid/data/zonas_departamentos:ro
      - ./model_sities/data/cookies_foursquare.json:/app/cookies_foursquare.json:ro
    networks:
      - scraper_network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  scraper_network:
    driver: bridge